name: "Setup Environment"
description: "Setup Debts project environment"
inputs:
  key-file-base64:
    description: 'Store key file encoded with base64'
    required: true
    default: ''
  google-services-file-base64:
    description: 'Google Services file encoded with base64'
    required: true
    default: ''
  google-play-publisher-file-base64:
    description: 'Google Play Publisher file'
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '20'
    - name: Github environment info
      run: |
        echo "GITHUB_ACTION=$GITHUB_ACTION"
        echo "GITHUB_RUN_ID=$GITHUB_RUN_ID"
        echo "GITHUB_RUN_NUMBER=$GITHUB_RUN_NUMBER"
        echo "GITHUB_SHA=$GITHUB_SHA"
        echo "GITHUB_ACTOR=$GITHUB_ACTOR"
      shell: bash
    - name: Setup environment
      run: |
        echo "${{ inputs.key-file-base64 }}" | base64 -d > ./app/debts.keystore;
        echo "${{ inputs.google-services-file-base64 }}" | base64 -d > ./app/google-services.json;
        echo "${{ inputs.google-play-publisher-file-base64 }}" | base64 -d > app/google-play-publisher.json;
      shell: bash
