package debts.core.common.android.buildconfig

// TODO: write Lint check to prevent direct usage of BuildConfig generated by Android
interface BuildConfigData {

    fun isDebug(): Boolean
    fun getApplicationId(): String
    fun getBuildType(): String
    fun getVersionCode(): Int
    fun getVersionName(): String
}
