name: Android CI

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - internal/*
      - release/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Github environment info
        run: |
          echo "GITHUB_ACTION=$GITHUB_ACTION"
          echo "GITHUB_RUN_ID=$GITHUB_RUN_ID"
          echo "GITHUB_RUN_NUMBER=$GITHUB_RUN_NUMBER"
          echo "GITHUB_SHA=$GITHUB_SHA"
          echo "GITHUB_ACTOR=$GITHUB_ACTOR"
      - name: Setup environment
        run: |
          echo "${{ secrets.DEBTS_KEY_FILE_BASE64 }}" | base64 -d > ./app/debts.keystore;
          echo "${{ secrets.DEBTS_GOOGLE_SERVICES_FILE_BASE64 }}" | base64 -d > ./app/google-services.json;
      - name: Static Code Analysis (Kotlin, detekt)
        run: ./gradlew detekt
        env:
          ENV_BUILD_ID: ${{ github.run_number }}
      - name: Lint (Android)
        run: ./gradlew lintDebug
      - name: Build
        env:
          DEBTS_STORE_KEY_ALIAS: ${{ secrets.DEBTS_STORE_KEY_ALIAS }}
          DEBTS_STORE_KEY_ALIAS_PASSWORD: ${{ secrets.DEBTS_STORE_KEY_ALIAS_PASSWORD }}
          DEBTS_STORE_KEY_FILE: ${{ secrets.DEBTS_STORE_KEY_FILE }}
          DEBTS_STORE_KEY_PASSWORD: ${{ secrets.DEBTS_STORE_KEY_PASSWORD }}
          DEBTS_FABRIC_API_KEY: ${{ secrets.DEBTS_FABRIC_API_KEY }}
        run: ./gradlew build
