name: Android CI

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - internal/*
      - release/*

jobs:
  static-analysis:
    uses: ./.github/workflows/static-analysis.yml
    secrets: inherit
  build:
    needs: static-analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup environment
        uses: ./.github/actions/setup-environment
        with:
          key-file-base64: "${{ secrets.DEBTS_KEY_FILE_BASE64 }}"
          google-services-file-base64: "${{ secrets.DEBTS_GOOGLE_SERVICES_FILE_BASE64 }}"
          google-play-publisher-file-base64: "${{ secrets.GOOGLE_PLAY_PUBLISHER }}"
      - name: Build Release
        env:
          ENV_BUILD_ID: ${{ github.run_number }}
          DEBTS_STORE_KEY_ALIAS: ${{ secrets.DEBTS_STORE_KEY_ALIAS }}
          DEBTS_STORE_KEY_ALIAS_PASSWORD: ${{ secrets.DEBTS_STORE_KEY_ALIAS_PASSWORD }}
          DEBTS_STORE_KEY_FILE: ${{ secrets.DEBTS_STORE_KEY_FILE }}
          DEBTS_STORE_KEY_PASSWORD: ${{ secrets.DEBTS_STORE_KEY_PASSWORD }}
        run: ./gradlew build
